### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by Sadi58** [kd8bny/cumulus#15]
I think it would be great if we could start cumulus by indicating location (and perhaps screen position, like 24px from top, 0px from right) as a command line option.
This would let us run 2 instances of cumulus to see the weather also in a second location (e.g. where a loved one lives ;-)

**Comment by vadrian89** [comment]
Unfortunately we cannot add this functionality in the current state, because the settings and location are stored in localstorage(browser localStorage) and every new instance would be connecting to the same data storage, will look into your ideea.
Thanks for your feedback.

**Comment by Sadi58** [comment]
Understood, thanks.
