### ISSUE TITLE
border

### ISSUE THREAD

**Issue by Sadi58** [kd8bny/cumulus#16]
I see a thick white border with a little more opacity on the right and at the bottom only.
IMHO it might look better without any border at all or a much thinner border all around.
Maybe one cannot argue against such design decisions, but then maybe the best is to make it optional ;-)

**Comment by vadrian89** [comment]
Can you provide a screenshot and also tell me what Desktop Environment are you using?  
There seem to be some issues with opacity on some DEs.

**Comment by Sadi58** [comment]
Ubuntu 16.10 (Unity 7) - No opacity issues as far as I can see.
I have the weather desktop widget on top right corner of my screen.
![screenshot from 2016-11-17 14-27-31](https://cloud.githubusercontent.com/assets/6375934/20387690/048b0f7a-acca-11e6-81eb-c6ae75a41415.png)

**Comment by vadrian89** [comment]
Strange, I'm using 16.04.1 and don't have this issue.  
I will look into this matter further.

**Comment by Sadi58** [comment]
Unfortunately, this time upgrading Ubuntu from 16.04 to 16.10 has brought more problems, although not critical, than improvements ;-)

**Comment by clairepresto** [comment]
I have the same issue after upgrade from 16.04 to 16.10 UbuntuMATE:
![screenshot at 2016-11-28 21-18-33](https://cloud.githubusercontent.com/assets/22969552/20664665/3efc535a-b5b0-11e6-8cf5-d2a350bb657e.png)

**Comment by Sadi58** [comment]
@clairepresto which cumulus version do you have?
I've just realized that I was using cumulus version **1.0.0** from here: https://github.com/kd8bny/cumulus/releases
And now, using version **1.0.73** from the PPA repository (`ppa:cumulus-team/cumulus`), I don't see that border any longer.
**Note:** It might be a good idea to include more details in `README.md`

**Comment by vadrian89** [comment]
Have updated the readme file to include the ppa

**Comment by clairepresto** [comment]
Yes I was using the version 1 .deb
removing & then reinstalling from ppa has corrected the issue.
Thanks, Cheers, Claire.

**Comment by Sadi58** [comment]
So we can close this issue then :-)
