### ISSUE TITLE
Possibility to set refresh rate

### ISSUE THREAD

**Issue by marksev1** [kd8bny/cumulus#19]
Would be really nice if it would be possible to set up at what kind of time interval it should refresh the values? Also what is the default value for doing that if it does it already?

**Comment by vadrian89** [comment]
The current refresh rate is 60 minutes, is so high because the apis used are free and quite limited in how many calls can be done Min/hour/day. Will add different intervals in a future build when I will make more providers available.

**Comment by vadrian89** [comment]
Can you please Tell me which version are You using?

**Comment by marksev1** [comment]
v 3.0.1
