### ISSUE TITLE
Sometimes, size of cumulus is greater than 300 x 500

### ISSUE THREAD

**Issue by archisman-panigrahi** [kd8bny/cumulus#5]
![screenshot from 2016-09-30 10 35 49](https://cloud.githubusercontent.com/assets/3063132/18981207/b0518b28-86f9-11e6-8e1a-39006916fae0.png)

The bug occurs as "Scattered Thunderstorms" occupies two lines.
The weather condition has to be forced to stay in one line. Otherwise, it can be moved to the centre so that it does not take more than one line.

**Comment by vadrian89** [comment]
I will make some test and check how it shows on the middle and come back.

**Comment by vadrian89** [comment]
I made a change which goes like this, if the length of the description length is longer than 15 then show the description 1 row bellow and align to middle. 
I will give it a test run when I get home, as I can only test it in browser at work, this evening and if it goes well I will commit it :)

**Comment by vadrian89** [comment]
Archisman I have made a pull request on Daryl's master branch, can you have a look and let me know if you approve so I can merge?

If everything is ok and you can merge, please do it and remake the ppa build if you want :), if no let me know what I fucked up :P.

**Comment by archisman-panigrahi** [comment]
The problem is that, I cannot find a place where "Scattered Thunderstorm" is occurring. I am going to accept the pull request for now, and will close this issue when I see the bug is fixed

**Comment by vadrian89** [comment]
![captura de ecran din 2016-10-01 22-14-19](https://cloud.githubusercontent.com/assets/8177798/19016510/eabe3bb8-8824-11e6-8440-feea7b16150a.png)

Above is a sample how it would look, manually set description, if a long description would occur
