### ISSUE TITLE
Changing to the first background color hides the Settings wheel

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [kd8bny/cumulus#7]
How to reproduce:
1. Click Settings wheel
2. Click on the first Background color (the one that is a gradient)
3. The Settings wheel is gone

**Comment by vadrian89** [comment]
Hello RicardoEPRodrigues, 

The installation was made through the debian package on the projects release page?  
If so, we are aware of that and fixed it, we also have made a ppa which will have the latest builds but it has some small bugs. 
We will share the ppa with the public in short time :), thanks for the report.
