### ISSUE TITLE
Open Weather Map not always providing data.

### ISSUE THREAD

**Issue by vadrian89** [kd8bny/cumulus#8]
Hi guys, 
Can you use Open Weather Map API as default weather source for Cumulus for a few days and let me know if you have issues with the app not loading weather at startup?   

Thanks.

**Comment by archisman-panigrahi** [comment]
I selected  Open Weather Map API, closed Cumulus. Now weather is not loading and API: Select is not working. Temporary solution: Click on sync, or change settings related to speed or unit.

But now I cannot reproduce it after changing location

**Comment by vadrian89** [comment]
The issue is because it doesn't detect the language and the data requests return errors.

If you look at the following [link](https://github.com/kd8bny/cumulus/blob/master/cumulus/CumulusWindow.py#L59), you can see where the system language is added, [at line 46](https://github.com/kd8bny/cumulus/blob/master/cumulus/CumulusWindow.py#L46) you can find where I declared the variable.  
Is there a way you can sneak the code right before the build?

**Comment by vadrian89** [comment]
Have you managed to think of a solution for this?
